#!/usr/bin/env python3
import boto3
import json
import sys
import os 

def get_lightsail_instances():
    name_prefix = os.getenv('ANSIBLE_LIGHTSAIL_PREFIX', 'jake-blog')
    client = boto3.client('lightsail')
    instances = client.get_instances()
    
    inventory = {
        "_meta": {
            "hostvars": {}
        },
        "all": {
            "hosts": [],
            "vars": {}
        },
        "blog": {
            "hosts": []
        }
    }
    
    for instance in instances['instances']:
        ip = instance['publicIpAddress']
        name = instance['name']
        
        inventory["_meta"]["hostvars"][ip] = {
            "ansible_host": ip,
            "instance_name": name
        }
        
        inventory["all"]["hosts"].append(ip)
        if name.startswith(name_prefix):
            inventory["blog"]["hosts"].append(ip)
    
    return inventory

def main():
    if len(sys.argv) > 1:
        if sys.argv[1] == '--list':
            print(json.dumps(get_lightsail_instances(), indent=2))
        elif sys.argv[1] == '--host':
            print(json.dumps({}))
    else:
        print(json.dumps(get_lightsail_instances(), indent=2))

if __name__ == '__main__':
    main()
