region            = "us-east-1"
availibility_zone = "a"
domain_name       = "staging.jake-henning.com"
instance_name     = "staging-jake-1"
blueprint_id      = "ubuntu_24_04"
bundle_id         = "nano_3_0"
bucket_name       = "staging-jakeblog-blog-image-cache"
